### ISSUE TITLE
dark mode in the flat parts of the app

### ISSUE THREAD

**Issue by Rose22** [amwatson/CitraVR#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

currently the whole app is white. can you add a dark mode setting so the app can be black or gray?

### Why would this feature be useful?

my eyes hurt XD

**Comment by amwatson** [comment]
Can you post a screenshot/screencapture?

**Comment by amwatson** [comment]
Oh, I think I understand what you're saying -- are you talking about the launcher background? 

I'd like to do that, actually -- all white looks pretty bad on these panels, and dark backgrounds look cool in general.

**Comment by Rose22** [comment]
> Oh, I think I understand what you're saying -- are you talking about the launcher background?
> 
> I'd like to do that, actually -- all white looks pretty bad on these panels, and dark backgrounds look cool in general.

yeah! sorry, seems our timezones are a bit far apart, so my replies are slow. the background of the game launcher and even the settings inside the launcher are all white. black or gray would be a lot nicer on the eyes! most android apps let you choose between "light mode" (white) or "dark mode" (gray). some let you choose black which is useful for OLED screens, but quest doesnt have OLED

**Comment by amwatson** [comment]
Yeah, interestingly, (non-VR) Citra locks the light/dark mode selection behind a "premium" feature. 

I can see about extracting that, but it may need to wait until after the merge from upstream

**Comment by Rose22** [comment]
oh wow, i didnt know that.. take your time, good luck with the merge!

**Comment by amwatson** [comment]
Hey! This is now fixed in [v0.4.0](https://github.com/amwatson/CitraVR/releases/tag/v0.4.0)
