### ISSUE TITLE
ability to stay in meta quest home when launching a game

### ISSUE THREAD

**Issue by Rose22** [amwatson/CitraVR#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

right now you can choose either a black void or passthrough, but i've seen apps like the Xbox Gamepass app somehow switch from flat to a custom view but stay inside the meta quest home environment. what i'm suggesting would be the ability to stay in whatever quest home you've chosen (in immersive mode/VR mode), and just play your games in there. not sure how hard this would be to implement and if it would go against what this app is meant to demonstrate?

### Why would this feature be useful?

general usability

**Comment by amwatson** [comment]
Unfortunately, I can't do that.  

Only first-party applications or 2D containers can use the Quest Home background as their app's background. Since CitraVR has to be immersive to get the 3D effect, among other things, it's unfortunately not possible to do what XBox did.

**Comment by pokeman-senpai12** [comment]
Would yhos maybe be possible if I used the normal citra apk.on andorid
