### ISSUE TITLE
Compatibility List - Migrate to Google Sheets

### ISSUE THREAD

**Issue by RickAndTired** [amwatson/CitraVR#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Compatibility List - Migrate to Google Sheets

Screenshot of an example:
![Screenshot from 2024-01-21 16-58-57](https://github.com/amwatson/CitraVR/assets/53553229/730c1d21-6ae8-4d05-b1f6-89405434c34a)

Here is my example Sheet - feel free to copy it if you'd like to migrate to Google Sheets
https://docs.google.com/spreadsheets/d/1fCX_KepDoUJ4ETAfdusELd2cISYF8u4avduPdpa_ofw/edit#gid=765233361

### Why would this feature be useful?

I think Google Sheets provides a better format for what the compatibility list is trying to accomplish.
It would allow easier additions and management. Simple drop down selections.
Better readability.

The first tab could be the main compatibility list that only editors can make changes to.
Second tab could allow anyone to submit results and editors could pull from there.
You could also create a Google Form for people to submit their results and it would output into the Sheet.

**Comment by amwatson** [comment]
that's a cool template -- I'd like to copy that, thanks! will look into

**Comment by amwatson** [comment]
Going to reopen because I just implemented this template. I will use this task for updating the README.

[Game Compatibility List (new)](https://docs.google.com/spreadsheets/d/1viN8_MWO1HW9QXlkT-TdCGQbH1g660mKsIp1ZTARdho/edit?usp=sharing)

It looks great! Thanks for sharing!
