### ISSUE TITLE
Mods Location

### ISSUE THREAD

**Issue by SalmonSays** [amwatson/CitraVR#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v0.3

### Description of Issue

I hope I'm not being obtuse, but I've looked through documentation and am struggling to find information about mod compatibility- to be specific I'm interested in running Majora's Mask: Restoration Project (https://restoration.zora.re) which specifies to "Right click on the game in the game list and select Open Mods Location. Copy code.bps and exheader.bin to that directory." Is there a protocol/directory for achieving this in CitraVR manually?

### Expected Behavior

I was hoping to right click on a game and access the mod directory.

### Reproduction Steps

I think the above description is pretty descriptive.

### Log File

There is no relevant log for this.

### System Configuration

HMD:
Quest 3

**Comment by ElBatallitas** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Affected Build(s)
> v0.3
> 
> ### Description of Issue
> I hope I'm not being obtuse, but I've looked through documentation and am struggling to find information about mod compatibility- to be specific I'm interested in running Majora's Mask: Restoration Project (https://restoration.zora.re) which specifies to "Right click on the game in the game list and select Open Mods Location. Copy code.bps and exheader.bin to that directory." Is there a protocol/directory for achieving this in CitraVR manually?
> 
> ### Expected Behavior
> I was hoping to right click on a game and access the mod directory.
> 
> ### Reproduction Steps
> I think the above description is pretty descriptive.
> 
> ### Log File
> There is no relevant log for this.
> 
> ### System Configuration
> HMD: Quest 3

Hey dude, I'm currently playing on Majora's restoration project in CitraVR.
It works, the only thing is that you need to manually create those folders to match the same structure that has on PC.

Let me know here if any issues, besides I recommend you to add 3d depth cheats to improve the stereoscopic. Search for: "Better Stereoscopic 3D" forum on gbatemp, there is one specifically for the restoration project.
(You add cheats by holding click on the game title.)
I recommend "Depth ++" cheat, and stereoscopic depth in CitraVR set to 25%
