### ISSUE TITLE
Issue with Screen Rendering on Oculus Quest 2

### ISSUE THREAD

**Issue by Vmarcelo49** [amwatson/CitraVR#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All of them

### Description of Issue

Something in the rendering is bugged on my quest 2, both screens are divided in half, the top screen shows half in one eye and half in the other but really far away from where it should be, the lower screen of the 3DS is only showing its left half.
the touch(or click with the cursor) still works where its black.
this happens in all games, tested on NSMB2, OOT
Tried reinstalling lots of times, also dont know if i changed something that could interfere with the emulator on the quest settings.

![oot](https://github.com/amwatson/CitraVR/assets/50602525/f8164e7f-bfd1-4eff-b447-b0aa1271f409)

### Expected Behavior

Normal rendering of the screens.

### Reproduction Steps

Opening the CitraVR app and starting a game with any configuration or rendering resolution.

### Log File

[citra_log.txt](https://github.com/amwatson/CitraVR/files/14073613/citra_log.txt)

### System Configuration

HMD:
Oculus Quest 2 64GB

**Comment by amwatson** [comment]
Should be fixed in [v0.3.2 (just released)](https://github.com/amwatson/CitraVR/releases/tag/v0.3.2).
