### ISSUE TITLE
Failed to fetch CitraVR, without Citra-Emu git repo.

### ISSUE THREAD

**Issue by SpectralDragon** [amwatson/CitraVR#67]
### Issue

Hi there! A bad news coming...
After ban YUZU, we also lost Citra-Emu github repo.  This affected current repository, because submodules looks to mother repo, like example:
```
fatal: repository 'https://github.com/citra-emu/ext-boost.git/' not found
fatal: clone of 'https://github.com/citra-emu/ext-boost.git' into submodule path 
```

What the future of CitraVR? 
We must be worry about Nintendo lawyers and what they will do next with this community...

**Comment by SHMAUS-Carter** [comment]
It may be possible to recover those subdirectories using the way back machine. But then you do lose the relevant history of those modules then again that's probably already lost.

**Comment by amwatson** [comment]
sorry about that! I've got copies stashed, so let me see what I can do

**Comment by drew-stott** [comment]
I am honestly generally heartbroken about the Yuzu / Citra situation but especially worried about how it will impact this project. It has been my favorite pass time for weeks now.

**Comment by justingoldberg** [comment]
[
magnet:?xt=urn:btih:59daa74a4d0172620ba9853b3282b50cf7607ec6&dn=citra-emu_GitHub_03-04-2024&tr=http%3A%2F%2Fbt1.archive.org%3A6969%2Fannounce&tr=http%3A%2F%2Fbt2.archive.org%3A6969%2Fannounce&ws=https%3A%2F%2Farchive.org%2Fdownload%2F&ws=http%3A%2F%2Fia600205.us.archive.org%2F13%2Fitems%2F&ws=http%3A%2F%2Fia800205.us.archive.org%2F13%2Fitems%2F](url)

**Comment by kvn1351** [comment]
There's a fork that has gained some foothold here https://github.com/RyzenDew/Lime-3DS-Emulator

**Comment by InitialXKO** [comment]
> There's a fork that has gained some foothold here https://github.com/RyzenDew/Lime-3DS-Emulator

Lime3DS is a project which aims to revive and continue work on Citra, a popular open-source Nintendo 3DS emulator which ceased development.

**Comment by amwatson** [comment]
This should be resolved now
