### ISSUE TITLE
Crashes on Mii Maker startup

### ISSUE THREAD

**Issue by NotGav05** [amwatson/CitraVR#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Thr latest beta build of Citra VR on Sidequest

### Description of Issue

When I open the mii maker . App file, it boots but crashes and closes within a few seconds. I've tried using multiple versions of mii maker and changing the file type to .3ds at the end. It still crashes.

### Expected Behavior

I should be able to launch mii maker and make miis for my emulated 3ds

### Reproduction Steps

launch mii maker.app/3ds using citra vr

### Log File

,

### System Configuration

HMD:
,

**Comment by Bobsmilk** [comment]
im having the same issue qwq

**Comment by amwatson** [comment]
This should be fixed in the latest, but let me know if you still see the issue: https://github.com/amwatson/CitraVR/releases/tag/v0.5.0
