### ISSUE TITLE
NO quest 3 controller only screen controller

### ISSUE THREAD

**Issue by walterleonardo** [amwatson/CitraVR#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v0.4.2

### Description of Issue

Try to play any game, and when the game starts, an additional window appears to the normal two screens in the NDS, in this new window you can see the controls a,b,y,x and trap, which work (If you point with the controllers and fire)... but I have not seen a way to play directly with the quest 3 controllers.
I have tried versions 0.4, 0.4.1 and 0.4.2

### Expected Behavior

Automatic switch to quest 3 controllers, if you dont have any other bluetooth controller connected. 

### Reproduction Steps

I will include a video. 

### Log File

Dont have. 

### System Configuration

HMD:
Quest 3

**Comment by walterleonardo** [comment]
[
![Screenshot 2024-05-31 at 19 02 57](https://github.com/amwatson/CitraVR/assets/512106/c9c2bfb0-a9cb-436c-8e47-e6af40adad33)
](url)

**Comment by walterleonardo** [comment]
I don't see this windows in the tutorials in internet... and I try uninstalling and reinstalling every and no result...
always appear this windows and only work if I do click into this windows buttons.

**Comment by InitialXKO** [comment]
Just another bug of V66 system

**Comment by walterleonardo** [comment]
Checked with a XBOX controller and work... but doesn't work with the Oculus Controllers.

**Comment by alremix** [comment]
A game window is also created separate from the main window, sometimes that window is meters away from the main window and it is not possible to move it or change its size

**Comment by amwatson** [comment]
Hey, I've got a fix in a new release: https://github.com/amwatson/CitraVR/releases/tag/v0.5.0
