### ISSUE TITLE
Broken 2D -> VR activity transition

### ISSUE THREAD

**Issue by geor-kasapidi** [amwatson/CitraVR#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v0.4.2

### Description of Issue

On quest OS v66 (beta), when launching game, VR mode is not starting - looks like OS ignores VR intent, and launches game in 2D mode.

### Expected Behavior

Game launches successfully in VR mode.

### Reproduction Steps

Update OS to v66 -> launch Citra VR -> Launch any game.

### Log File

[   0.000111] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_createLogFile:593: Logging backend initialised
[   0.000162] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_logUserDirectory:600: User directory path: content://com.android.externalstorage.documents/tree/primary%3ADownload%2FCitra
[   0.025999] Config <Info> main/jni/config.cpp:LoadINI:59: Successfully loaded /config/config.ini.vr
[   0.026106] Config <Info> main/jni/config.cpp:ReadValues:277: HMD type: Quest 3
[   0.052113] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_logDeviceInfo:747: Citra Version: 611fc9a | master-611fc9ace-dirty
[   0.052295] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_logDeviceInfo:748: Host CPU: Unknown
[   0.052305] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_logDeviceInfo:750: Host OS: Android API level 32
[   0.166313] VR <Info> main/jni/vr/vr_main.cpp:Java_org_citra_citra_1emu_vr_VrActivity_nativeOnCreate:944: nativeOnCreate -5476376627715040512
[   0.166484] VR <Info> main/jni/vr/vr_main.cpp:MainLoop:181: VR Extra Performance Mode: disabled
[   0.222021] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.487493] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.523594] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.602627] VR <Info> main/jni/vr/layers/GameSurfaceLayer.cpp:CreateSwapchain:480: GameSurfaceLayer: Creating swapchain of size 1500x1440 (500x480 with resolution factor 3x)
[   0.604699] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_surfaceChanged:305: Surface changed
[   0.605395] Frontend <Info> main/jni/native.cpp:RunCitra:137: Citra starting...
[   0.625501] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_surfaceChanged:305: Surface changed
[   0.657556] Config <Info> main/jni/config.cpp:LoadINI:59: Successfully loaded /config/config.ini.vr
[   0.657646] Config <Info> main/jni/config.cpp:ReadValues:277: HMD type: Quest 3
[   0.701619] Service.FS <Error> core/file_sys/ncch_container.cpp:LoadHeader:157: 16384
[   0.701637] Config <Info> common/settings.cpp:LogSettings:83: Citra Configuration:
[   0.701640] Config <Info> common/settings.cpp:operator():80: Core_UseCpuJit: true
[   0.701642] Config <Info> common/settings.cpp:operator():80: Core_CPUClockPercentage: 100
[   0.701643] Config <Info> common/settings.cpp:operator():80: Renderer_UseGLES: true
[   0.701645] Config <Info> common/settings.cpp:operator():80: Renderer_GraphicsAPI: OpenGL
[   0.701647] Config <Info> common/settings.cpp:operator():80: Renderer_AsyncShaders: false
[   0.701648] Config <Info> common/settings.cpp:operator():80: Renderer_AsyncPresentation: true
[   0.701667] Config <Info> common/settings.cpp:operator():80: Renderer_SpirvShaderGen: true
[   0.701668] Config <Info> common/settings.cpp:operator():80: Renderer_Debug: false
[   0.701669] Config <Info> common/settings.cpp:operator():80: Renderer_UseHwShader: true
[   0.701670] Config <Info> common/settings.cpp:operator():80: Renderer_ShadersAccurateMul: true
[   0.701670] Config <Info> common/settings.cpp:operator():80: Renderer_UseShaderJit: true
[   0.701672] Config <Info> common/settings.cpp:operator():80: Renderer_UseResolutionFactor: 0
[   0.701673] Config <Info> common/settings.cpp:operator():80: Renderer_FrameLimit: 100
[   0.701673] Config <Info> common/settings.cpp:operator():80: Renderer_VSyncNew: true
[   0.701674] Config <Info> common/settings.cpp:operator():80: Renderer_PostProcessingShader: none (builtin)
[   0.701675] Config <Info> common/settings.cpp:operator():80: Renderer_FilterMode: false
[   0.701676] Config <Info> common/settings.cpp:operator():80: Renderer_TextureFilter: None
[   0.701677] Config <Info> common/settings.cpp:operator():80: Renderer_TextureSampling: GameControlled
[   0.701680] Config <Info> common/settings.cpp:operator():80: Stereoscopy_Render3d: 1
[   0.701680] Config <Info> common/settings.cpp:operator():80: Stereoscopy_Factor3d: 50
[   0.701681] Config <Info> common/settings.cpp:operator():80: Stereoscopy_MonoRenderOption: 0
[   0.701682] Config <Info> common/settings.cpp:operator():80: Layout_LayoutOption: 6
[   0.701683] Config <Info> common/settings.cpp:operator():80: Layout_SwapScreen: false
[   0.701683] Config <Info> common/settings.cpp:operator():80: Layout_UprightScreen: false
[   0.701686] Config <Info> common/settings.cpp:operator():80: Layout_LargeScreenProportion: 4
[   0.701687] Config <Info> common/settings.cpp:operator():80: Utility_DumpTextures: false
[   0.701687] Config <Info> common/settings.cpp:operator():80: Utility_CustomTextures: false
[   0.701688] Config <Info> common/settings.cpp:operator():80: Utility_PreloadTextures: false
[   0.701688] Config <Info> common/settings.cpp:operator():80: Utility_AsyncCustomLoading: true
[   0.701689] Config <Info> common/settings.cpp:operator():80: Utility_UseDiskShaderCache: true
[   0.701689] Config <Info> common/settings.cpp:operator():80: Audio_Emulation: HLE
[   0.701690] Config <Info> common/settings.cpp:operator():80: Audio_OutputType: 0
[   0.701691] Config <Info> common/settings.cpp:operator():80: Audio_OutputDevice: auto
[   0.701692] Config <Info> common/settings.cpp:operator():80: Audio_InputType: 0
[   0.701692] Config <Info> common/settings.cpp:operator():80: Audio_InputDevice: auto
[   0.701693] Config <Info> common/settings.cpp:operator():80: Audio_EnableAudioStretching: false
[   0.701693] Config <Info> common/settings.cpp:operator():80: Camera_OuterRightName: ndk
[   0.701694] Config <Info> common/settings.cpp:operator():80: Camera_OuterRightConfig: _back
[   0.701695] Config <Info> common/settings.cpp:operator():80: Camera_OuterRightFlip: 0
[   0.701695] Config <Info> common/settings.cpp:operator():80: Camera_InnerName: ndk
[   0.701696] Config <Info> common/settings.cpp:operator():80: Camera_InnerConfig: _front
[   0.701696] Config <Info> common/settings.cpp:operator():80: Camera_InnerFlip: 0
[   0.701697] Config <Info> common/settings.cpp:operator():80: Camera_OuterLeftName: ndk
[   0.701697] Config <Info> common/settings.cpp:operator():80: Camera_OuterLeftConfig: _back
[   0.701698] Config <Info> common/settings.cpp:operator():80: Camera_OuterLeftFlip: 0
[   0.701698] Config <Info> common/settings.cpp:operator():80: DataStorage_UseVirtualSd: true
[   0.701699] Config <Info> common/settings.cpp:operator():80: DataStorage_UseCustomStorage: false
[   0.701700] Config <Info> common/settings.cpp:operator():80: System_IsNew3ds: true
[   0.701700] Config <Info> common/settings.cpp:operator():80: System_LLEApplets: false
[   0.701701] Config <Info> common/settings.cpp:operator():80: System_RegionValue: -1
[   0.701701] Config <Info> common/settings.cpp:operator():80: System_PluginLoader: false
[   0.701702] Config <Info> common/settings.cpp:operator():80: System_PluginLoaderAllowed: true
[   0.701702] Config <Info> common/settings.cpp:operator():80: Debugging_DelayStartForLLEModules: true
[   0.701703] Config <Info> common/settings.cpp:operator():80: Debugging_UseGdbstub: false
[   0.701703] Config <Info> common/settings.cpp:operator():80: Debugging_GdbstubPort: 24689
[   0.773400] VR <Info> main/jni/vr/vr_main.cpp:HandleSessionStateChanges:706: HandleSessionStateChanges(): Set clock levels to CPU:50, GPU:75
[   0.773515] Frontend <Info> main/jni/native.cpp:Java_org_citra_citra_1emu_NativeLibrary_surfaceChanged:305: Surface changed
[   0.773580] VR <Info> main/jni/vr/vr_main.cpp:Frame:302: Time to first frame: 607 ms
[   1.120576] Audio.DSP <Info> audio_core/hle/aac_decoder.cpp:AACDecoder:27: Created FAAD2 AAC decoder.
[   1.145929] RPC_Server <Info> core/rpc/rpc_server.cpp:RPCServer:14: Starting RPC server.
[   1.146060] RPC_Server <Info> core/rpc/rpc_server.cpp:HandleRequestsLoop:104: Request handler started.
[   1.164511] Audio.Sink <Info> audio_core/cubeb_sink.cpp:StateCallback:135: Cubeb Audio Stream Started
[   1.287413] Service.HTTP <Error> core/hle/service/http/http_c.cpp:DecryptClCertA:1974: ClCertA file missing
[   1.287919] Render.OpenGL <Info> video_core/renderer_opengl/gl_driver.cpp:ReportDriverInfo:135: GL_VERSION: OpenGL ES 3.2 V@0767.0 (GIT@b0ed28cdeb, I87200b92e5, 1709271149) (Date:02/29/24)
[   1.287975] Render.OpenGL <Info> video_core/renderer_opengl/gl_driver.cpp:ReportDriverInfo:136: GL_VENDOR: Qualcomm
[   1.288004] Render.OpenGL <Info> video_core/renderer_opengl/gl_driver.cpp:ReportDriverInfo:137: GL_RENDERER: Adreno (TM) 740
[   1.361148] Render.OpenGL <Info> video_core/renderer_opengl/gl_blit_helper.cpp:BlitHelper:76: Texture views are unsupported, reinterpretation will do intermediate copy
[   1.383340] Loader <Info> core/loader/ncch.cpp:Load:268: Program ID: 0004000000081600
[   1.383427] Service.FS <Warning> core/file_sys/ncch_container.cpp:OpenFile:126: Failed to open /sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/00081600/content/00000000.app
[   1.465770] Loader <Info> core/hle/kernel/process.cpp:ParseKernelCaps:196: ExHeader kernel version: 2.31
[   1.507523] Service.FS <Info> core/file_sys/ncch_container.cpp:LoadSectionExeFS:506: Attempting to load logo from the ExeFS
[   1.560221] Render.OpenGL <Info> video_core/renderer_opengl/gl_shader_disk_cache.cpp:LoadTransferable:175: Found a transferable disk cache with 8 entries
[   1.560699] Render.OpenGL <Info> video_core/renderer_opengl/gl_shader_disk_cache.cpp:LoadPrecompiledFile:282: Found a precompiled disk cache with 6 decompiled entries and 6 binary entries
[   2.129116] Service.SRV <Warning> core/hle/service/sm/srv.cpp:RegisterClient:63: (STUBBED) called. Caller PID=11
[   2.253272] Service.SRV <Warning> core/hle/service/sm/srv.cpp:EnableNotification:85: (STUBBED) called
[   2.266591] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:OverrideDefaultDaemons:186: (STUBBED) bit_mask=0x0000000F
[   2.267936] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:SuspendDaemons:74: (STUBBED) bit_mask=0x00000006
[   2.289894] Input <Error> main/jni/ndk_motion.cpp:operator():145: Could not find sensor of type 1
[   2.289945] Input <Error> main/jni/ndk_motion.cpp:operator():145: Could not find sensor of type 4
[   2.297821] Service.FS <Error> core/file_sys/archive_extsavedata.cpp:OpenFile:138: /nand/data/00000000000000000000000000000000/extdata/00048000/F000000B/user/ublg.lst not found
[   2.300935] Service.APT <Warning> core/hle/service/apt/apt.cpp:NotifyToWait:343: (STUBBED) app_id=768
[   2.306488] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:694: (STUBBED) called command=0X00000007, input_size=0X00000004, output_size=0X00000001
[   2.307645] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:694: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[   2.308208] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:694: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[   2.309119] Service.FRD <Warning> core/hle/service/frd/frd.cpp:SetClientSdkVersion:233: (STUBBED) called, version: 0x020506C8
[   2.309546] Service.FRD <Warning> core/hle/service/frd/frd.cpp:GetMyPresence:41: (STUBBED) called
[   2.310071] Service.APT <Warning> core/hle/service/apt/apt.cpp:SetAppCpuTimeLimit:715: (STUBBED) called, must_be_one=1, value=30
[   2.310432] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:SuspendScheduler:98: (STUBBED) perform_in_background=false
[   2.336094] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:194: Delay generator was not initalized. Using default
[   2.370697] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:194: Delay generator was not initalized. Using default
[   2.708690] Service.SRV <Warning> core/hle/service/sm/srv.cpp:Subscribe:212: (STUBBED) called, notification_id=0x209
[   2.711601] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:194: Delay generator was not initalized. Using default
[   2.714077] Service.FS <Error> ./core/file_sys/file_backend.h:GetReadDelayNs:51: Delay generator was not initalized. Using default
[   2.723332] Service.HID <Warning> core/hle/service/hid/hid.cpp:GetGyroscopeLowCalibrateParam:403: (STUBBED) called
[   2.740045] Service.CFG <Info> core/hle/service/cfg/cfg.cpp:UpdatePreferredRegionCode:674: Preferred region code set to 2
[   3.150993] Service.FS <Error> ./core/file_sys/archive_backend.h:GetOpenDelayNs:194: Delay generator was not initalized. Using default
[   3.151149] Service.FS <Warning> core/file_sys/archive_ncch.cpp:OpenFile:145: Mii data file missing. Loading open source replacement from memory
[   3.237467] Service.CECD <Warning> core/hle/service/cecd/cecd.cpp:GetCecInfoEventHandle:714: (STUBBED) called
[   3.259346] Service.FS <Error> core/file_sys/savedata_archive.cpp:OpenFile:75: Non-existing file /nand/data/00000000000000000000000000000000/sysdata/00010034/00000000/BOSS_SV.db can't be open without mode create.
[   3.259486] Service.FS <Error> core/file_sys/savedata_archive.cpp:OpenFile:75: Non-existing file /nand/data/00000000000000000000000000000000/sysdata/00010034/00000000/BOSS_SS.db can't be open without mode create.
[   3.259488] Service.BOSS <Error> core/hle/service/boss/online_service.cpp:InitializeSession:104: Could not open BOSS database.
[   3.268183] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenArchive:333: failed to get a handle for archive archive_id=0x00000006 archive_path=[Binary: 010000000703000000000000]
[   3.296619] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:694: (STUBBED) called command=0X00000007, input_size=0X00000004, output_size=0X00000001
[   3.308849] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:694: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[   3.386249] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:460: Firmware hash: 0x17ba3a64884d5dc7
[   3.386268] Service.DSP <Info> audio_core/hle/hle.cpp:LoadComponent:464: Structures hash: 0xd194fc96db654a27
[   3.386272] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:LoadComponent:192: called size=0xBEA4, prog_mask=0x00FF, data_mask=0x00FF
[   3.387461] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:RegisterInterruptEvents:259: Registered interrupt=2, channel=2, event=event-00223a64
[   3.387904] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:GetSemaphoreEventHandle:275: (STUBBED) called
[   3.388333] Service.DSP <Warning> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphoreMask:285: (STUBBED) called mask=0x2000
[   3.388960] Audio.DSP <Info> audio_core/hle/hle.cpp:PipeWrite:224: Application has requested initialization of DSP hardware
[   3.389241] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
[   3.391891] Service.DSP <Info> core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000
[   3.717550] Service.FRD <Warning> core/hle/service/frd/frd.cpp:GetMyFriendKey:95: (STUBBED) called
[   3.719045] Service.FRD <Warning> core/hle/service/frd/frd.cpp:GetMyMii:139: (STUBBED) called
[   3.720167] Service.FRD <Warning> core/hle/service/frd/frd.cpp:GetMyProfile:151: (STUBBED) called
[   3.720885] Service.FRD <Warning> core/hle/service/frd/frd.cpp:GetFriendKeyList:56: (STUBBED) called, unknown=0, frd_count=100
[   4.146084] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenArchive:333: failed to get a handle for archive archive_id=0x00000004 archive_path=[Empty]
[   4.146084] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenArchive:333: failed to get a handle for archive archive_id=0x00000004 archive_path=[Empty]
[   6.430854] Debug <Critical> video_core/renderer_opengl/gl_shader_util.cpp:operator():110: Assertion Failed!
Shader not linked

### System Configuration

HMD:
Meta Quest 3

**Comment by InitialXKO** [comment]
It seems that the affected build version is not only v0.4.2, but also all other build versions have the same situation, so the problem should come from the v66 firmware.

**Comment by lvonasek** [comment]
@amwatson There is a simple fix for this one:
```
             <intent-filter>
+                <action android:name="android.intent.action.VIEW" />
                 <category android:name="com.oculus.intent.category.VR" />
                 <category android:name="android.intent.category.LAUNCHER" />
             </intent-filter>
```

Thank you for https://github.com/amwatson/2DVrHybrid, it made my life easier 💖

**Comment by amwatson** [comment]
Hey, I've got a fix in a new release: https://github.com/amwatson/CitraVR/releases/tag/v0.5.0
