### ISSUE TITLE
Can't use touch screen at all since quest 3 update'

### ISSUE THREAD

**Issue by chaoslion1984** [amwatson/CitraVR#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v0.2.4

### Description of Issue

Not only can you not use the quest 3 touch controllers since the latest quest 3 update, but the touch screen cannot be interacted with at all either.

### Expected Behavior

Touch screen in VR unresponsive

### Reproduction Steps

Just using the software regularly produces this result.

### Log File

Don't have one

### System Configuration

HMD:

**Comment by amwatson** [comment]
This should be fixed on v0.5.0, but let me know if you run into issues:  https://github.com/amwatson/CitraVR/releases/tag/v0.5.0

**Comment by amwatson** [comment]
Hey, I've got a fix in a new release: https://github.com/amwatson/CitraVR/releases/tag/v0.5.0

**Comment by st-ivan** [comment]
> Hey, I've got a fix in a new release: https://github.com/amwatson/CitraVR/releases/tag/v0.5.0

hi amwatson, thanks for you work.. im loving this emulator. i just ran into an issue, i had old version installed and when i upgraded it all games were stutering so i went ahead reset all settings and now the games run fine but the touch control stops working as soon as i run a game.. meaning i cant touch the lower screen and buttons dont work

**Comment by skyehye33** [comment]
> Hey, I've got a fix in a new release: https://github.com/amwatson/CitraVR/releases/tag/v0.5.0

Hi, I have this exact issue but just with Nintendogs and Cats titles, I am not able to pet my dogs and it seems a lot of the petting and brushing mechanics are broken. Should I open a new issue? I don't use fllat2VR also, so I dont know how that suggestion could help me fix the issue for the newest vers of CitraVR.
Btw I'm using the android version on Q3

Thanks for any help!
