### ISSUE TITLE
ability to close a game and return to menu

### ISSUE THREAD

**Issue by Rose22** [amwatson/CitraVR#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

it'd be nice if you could close the game you're playing and return to citravr's menu, without having to quit citravr itself

### Why would this feature be useful?

general usability

**Comment by jakedowns** [comment]
soon™

**Comment by amwatson** [comment]
I've added a hotkey binding option to quit to menu for gamepads in v0.4.2 (latest), under Settings > Gamepad. An in-game button option will come in a future release

**Comment by amwatson** [comment]
Going to close because I'm aware of the request and the feature is now available: I'm aware of the desire for a more universal UI option, though
